### ISSUE TITLE
Lot issues since update to Arduino 1.8.16 and Teensyduino 1.55

### ISSUE THREAD

**Issue by BOBILLIER** [wwatson4506/UsbMscFat#15]
I work fine with your library with Arduino 1.8.15 and Teensyduino 1.54, but since my update to Arduino 1.8.16 and Teensyduino 1.55, I obtain lots of errors. (Show errors rapport
[Compilation errors.txt](https://github.com/wwatson4506/UsbMscFat/files/7184021/Compilation.errors.txt)
).

**Comment by BOBILLIER** [comment]
Solved with the integration of New Branch - FS_integration proposed by mjs513in the previous issue #14.
